# Lang
language: zh-CN

# Dark Mode
dark: false

# Header
menu:
  主页: /
  日志: /archives
  应用: /applications
  关于: /about
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics: "UA-78885574-1"
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: Another E.N.
description: I am a mobile developer, Apple-oriented programmer, Swifter.
links:
  Blog: /archives
  GitHub: https://github.com/anotheren/
  App: /applications
  #Instagram: http://instagram.com/
  #Facebook: http://facebook.com/
  #Twitter : http://twitter.com/


# Info
archive_footer_content: <p>本站点采用 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享 署名-非商业性使用-相同方式共享 4.0 国际 许可协议</a></br>基于 <a href="https://hexo.io">Hexo</a> 搭建，感谢 <a href="https://www.vultr.com/?ref=6871895/">Vultr</a> 提供的托管服务</br>© 2017 - 本站由 <a href="https://anotheren.com">@anotheren</a> 创建，使用 <a href="https://github.com/anotheren/hexo-theme-typing">typing</a> 主题</p>
post_footer_content: <p>本站点采用 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享 署名-非商业性使用-相同方式共享 4.0 国际 许可协议</a></br>基于 <a href="https://hexo.io">Hexo</a> 搭建，感谢 <a href="https://www.vultr.com/?ref=6871895/">Vultr</a> 提供的托管服务</br>© 2017 - 本站由 <a href="https://anotheren.com">@anotheren</a> 创建，使用 <a href="https://github.com/anotheren/hexo-theme-typing">typing</a> 主题</p>
